bio = ['No friends',
       'Stays at home all day',
       'Never gives me a discount',
       'Made me angel cry',
       'Like pp in there mouth',
       'Shoves long things up there ass',
       'Sells there body for money',
       'A slut',
       'Very gay',
       'Buy buckets of cum from suppliers',
       'No relationship',
       'watches under aged porn',
       'Nobody loves them',
       'Falls down the stairs with cum on there hands',
       'Still wets the bed',
       'Adopted',
       'Still looking for love',
       'Cant live without there body pillow',
       'Teachers pet',
       'Skinny shrimp',
       'Supports Nazi',
       'Cant wank',
       'Mommies boy',
       'Cant socialize',
       'Not needed',
       'PP is smaller than a atom']
