roasts = ['You’re the reason God created the middle finger.',
          'You’re a grey sprinkle on a rainbow cupcake.',
          'If your brain was dynamite, there wouldn’t be enough to blow your hat off.',
          'You are more disappointing than an unsalted pretzel.',
          'Light travels faster than sound which is why you seemed bright until you spoke.',
          'We were happily married for one month, but unfortunately we’ve been married for 10 years.',
          'Your kid is so annoying, he makes his Happy Meal cry.',
          'You have so many gaps in your teeth it looks like your tongue is in jail.',
          'Your secrets are always safe with me. I never even listen when you tell me them.',
          'I’ll never forget the first time we met. But I’ll keep trying.',
          'I forgot the world revolves around you. My apologies, how silly of me.',
          'I only take you everywhere I go just so I don’t have to kiss you goodbye.',
          'Hold still. I’m trying to imagine you with personality.',
          'Our kid must have gotten his brain from you! I still have mine.',
          'Your face makes onions cry.',
          'The only way my husband would ever get hurt during an activity is if the TV exploded.',
          'You look so pretty. Not at all gross, today.',
          'Her teeth were so bad she could eat an apple through a fence.',
          'I’m not insulting you, I’m describing you.',
          'I’m not a nerd, I’m just smarter than you.',
          'Keep rolling your eyes, you might eventually find a brain.',
          'Your face is just fine but we’ll have to put a bag over that personality.',
          'You bring everyone so much joy, when you leave the room.',
          'I thought of you today. It reminded me to take out the trash.',
          'Don’t worry about me. Worry about your eyebrows.',
          'there is approximately 1,010,030 words in the language english, but i cannot string enough words together to express how much i want to hit you with a chair']

deaths = ['rolling out of the bed and the demon under the bed ate them.',
          'getting impaled on the bill of a swordfish.',
          'falling off a ladder and landing head first in a water bucket.',
          'his own explosive while trying to steal from a condom dispenser.',
          'a coconut falling off a tree and smashing there skull in.',
          'taking a selfie with a loaded handgun shot himself in the throat.',
          'shooting himself to death with gun carried in his breast pocket.',
          'getting crushed while moving a fridge freezer.',
          'getting crushed by his own coffins.',
          'getting crushed by your partner.',
          'laughing so hard at The Goodies Ecky Thump episode that he died of heart failure.',
          'getting run over by his own vehicle.',
          'car engine bonnet shutting on there head.',
          'tried to brake check a train.',
          'dressing up as a cookie and cookie monster ate them.',
          'trying to re-act Indiana Jones, died from a snake bite.',
          'tried to short circuit me, not that easy retard',
          'tried to fight a bear with there hands',
          'getting Billy Heartied in the ball sacks'
          ]
