# !/usr/bin/python

"""
Copyright ©️: 2020 Seniatical / _-*™#7519
License: Apache 2.0
A permissive license whose main conditions require preservation of copyright and license notices.
Contributors provide an express grant of patent rights.
Licensed works, modifications, and larger works may be distributed under different terms and without source code.
FULL LICENSE CAN BE FOUND AT:
    https://www.apache.org/licenses/LICENSE-2.0.html
Any violation to the license, will result in moderate action
You are legally required to mention (original author, license, source and any changes made)
"""

facts = [
    'McDonald’s once made bubblegum-flavored broccoli',
    'Some fungi create zombies, then control their minds',
    'The first oranges weren’t orange',
    'There’s only one letter that doesn’t appear in any U.S. state name',
    'A cow-bison hybrid is called a “beefalo”',
    'Johnny Appleseed’s fruits weren’t for eating',
    'Samsung tests phone durability with a butt-shaped robot',
    'The “Windy City” name has nothing to do with Chicago weather',
    'Peanuts aren’t technically nuts',
    'Armadillo shells are bulletproof',
    'Firefighters use wetting agents to make water wetter',
    'The longest English word is 189,819 letters long',
    '“Running amok” is a medically recognized mental condition',
    'Octopuses lay 56,000 eggs at a time',
    'Cats have fewer toes on their back paws',
    'Kleenex tissues were originally intended for gas masks',
    'Blue whales eat half a million calories in one mouthful',
    'That tiny pocket in jeans was designed to store pocket watches',
    'Turkeys can blush',
    'Most Disney characters wear gloves to keep animation simple',
    'The man with the world’s deepest voice can make sounds humans can’t hear',
    'The current American flag was designed by a high school student',
    'Cows don’t have upper front teeth',
    'Thanks to 3D printing, NASA can basically “email” tools to astronauts',
    'Only a quarter of the Sahara Desert is sandy',
    'There were active volcanoes on the moon when dinosaurs were alive',
    'Dogs sniff good smells with their left nostril',
    'Avocados were named after reproductive organs',
    'T. S. Eliot wore green makeup',
    'The word “fizzle” started as a type of fart',
    'You only have two body parts that never stop growing',
    'No number before 1,000 contains the letter A',
    'The # symbol isn’t officially called hashtag or pound',
    'The French have their own name for a “French kiss”',
    'You can thank the Greeks for calling Christmas “Xmas”',
    'Movie trailers originally played after the movie',
    'Mercedes invented a car controlled by joystick',
    'The U.S. government saved every public tweet from 2006 through 2017',
    'H&M actually does stand for something',
    'Theodore Roosevelt had a pet hyena',
    'Cap’n Crunch’s full name is Horatio Magellan Crunch',
    'The CIA headquarters has its own Starbucks, but baristas don’t write names on the cups',
    'Giraffe tongues can be 20 inches long',
    'There’s only one U.S. state capital without a McDonald’s',
    'Europeans were scared of eating tomatoes when they were introduced',
    'Humans aren’t the only animals that dream',
    'The inventor of the microwave appliance only received $2 for his discovery',
    'The Eiffel Tower can grow more than six inches during the summer',
    'Glitter was made on a ranch',
    'Creature is a vegetarian',
    'Medical errors are a top cause of death',
    'Sloths have more neck bones than giraffes',
    'Bees can fly higher than Mount Everest',
    'Ancient Egyptians used dead mice to ease toothaches',
    'Paint used to be stored in pig bladders',
    'Humans have jumped further than horses in the Olympics',
    'The Terminator script was sold for $1',
    'Pigeon poop is the property of the British Crown',
    'Onions were found in the eyes of an Egyptian mummy',
    'Abraham Lincoln was a bartender',
    'Beethoven never knew how to multiply or divide',
    'Japan released sushi-inspired KitKats',
    'The word aquarium means “watering place for cattle” in Latin',
    'An espresso maker was sent into space in 2015',
    'An employee at Pixar accidentally deleted a sequence of Toy Story 2 during production',
    'Steve Jobs, Steve Wozniak, and Ron Wayne started Apple Inc. on April Fools’ Day',
    'The inventor of the tricycle personally delivered two to Queen Victoria',
    'Your brain synapses shrink while you sleep',
    'A waffle iron inspired one of the first pairs of Nikes',
    'Boars wash their food',
    'Baseball umpires used to sit in rocking chairs',
    'The first commercial passenger flight lasted only 23 minutes',
    'The world’s first novel ends mid-sentence',
    'The French-language Scrabble World Champion doesn’t speak French',
    'A woman called the police when her ice cream didn’t have enough sprinkles',
    'Uncle Ben’s rice was airdropped to World War II troops',
    'The British Empire was the largest empire in world history',
    'South American river turtles talk in their eggs',
    'Penicillin was first called “mold juice”',
    'The first stroller was pulled by a goat',
    'May 20, 1873, is the “birthday” of blue jeans',
    '170-year-old bottles of champagne were found at the bottom of the Baltic Sea',
    'The MGM lion roar is trademarked',
    'Neil Armstrong’s hair was sold in 2004 for $3,000',
    'Irish bars used to be closed on St. Patrick’s Day',
    'Nikola Tesla hated pearls',
    'Thomas Edison is the reason you love cat videos',
    'Brad Pitt suffered an ironic injury on a film set',
    'Pregnancy tests date back to 1350 BCE',
    'Martin Luther King Jr. got a C in public speaking',
    'Bananas glow blue under black lights',
    'Bees can make colored honey',
    'Wimbledon tennis balls are kept at 68 degrees Fahrenheit',
    'Adult cats are lactose intolerant',
    'Albert Einstein’s eyeballs are in New York City',
    'The Pope can’t be an organ donor',
    ' A one-armed player scored the winning goal in the first World Cup',
    'The world’s oldest toy is a stick',
    'When you were born, you were, for a moment, the youngest person on earth.',
    'Sea otters hold hands when they sleep to keep from drifting apart.',
    'The elements that we are composed of were formed in the interiors of collapsing stars. We are all made of star dust.',
]

bot_facts = (
    'Your server is seen in the support server once you add me!',
    'I automatically report unknown bugs!', 'I am fully tunable!',
    'I was made for fun!', 'I am still expanding with new features',
    'You can contribute to Karen by opening a pull request on the repo',
    'Show me an error code in the support server for a special role!',
    'My Code was lost 10 times before! This is why you may loose your data from time to time.'
)
