# !/usr/bin/python

"""
Copyright ©️: 2020 Seniatical / _-*™#7519
License: Apache 2.0
A permissive license whose main conditions require preservation of copyright and license notices.
Contributors provide an express grant of patent rights.
Licensed works, modifications, and larger works may be distributed under different terms and without source code.
FULL LICENSE CAN BE FOUND AT:
    https://www.apache.org/licenses/LICENSE-2.0.html
Any violation to the license, will result in moderate action
You are legally required to mention (original author, license, source and any changes made)
"""

jokes = ['I told my wife she was drawing her eyebrows to high.\n\nShe looked suprised.',
        'And the Lord said unto John,"Come forth and you will receive eternal life\nBut John came fifth,and won a toaster."',
        'I threw a boomerang a few years ago.\nI now live in constant fear',
        'What is the best thing about Switzerland?\n\nI dont know the flag is a big plus',
        'I invented a new word!\n\nPlagiarism!',
        'Did you hear about the mathematician who’s afraid of negative numbers?\n\nHe’ll stop at nothing to avoid them.',
        'Why do we tell actors to “break a leg?”\n\nBecause every play has a cast.',
        'Helvetica and Times New Roman walk into a bar\n\n“Get out of here!” shouts the bartender. “We don’t serve your type.”',
        'Yesterday I saw a guy spill all his Scrabble letters on the road.\n\nI asked him, “What’s the word on the street?”',
        'How many times can you subtract 10 from 100?\n\nOnce. The next time you would be subtracting 10 from 90.',
        'Hear about the new restaurant called Karma?\n\nThere’s no menu: You get what you deserve.',
        'A woman in labour suddenly shouted, “Shouldn’t! Wouldn’t! Couldn’t! Didn’t! Can’t!”\n\n“Don’t worry,” said the doctor. “Those are just contractions.”',
        'A bear walks into a bar and says, “Give me a whiskey… and a cola.”\n\n“Why the big pause?” asks the bartender. The bear shrugged. “I’m not sure. I was born with them.”',
        'Did you hear about the actor who fell through the floorboards?\n\nHe was just going through a stage.',
        'Did you hear about the claustrophobic astronaut?\n\nHe just needed a little space.',
        'Why don’t scientists trust atoms?\n\nBecause they make up everything.',
        'Why did the chicken go to the séance?\n\nTo get to the other side.',
        'Where are average things manufactured?\n\nThe satisfactory.',
        'How do you drown a hipster?\n\nThrow him in the mainstream.',
        'What sits at the bottom of the sea and twitches?\n\nA nervous wreck.',
        'What does a nosy pepper do?\n\nGets jalapeño business!',
        'Why are pirates called pirates?\n\nBecause they arrgh!',
        'Why can’t you explain puns to kleptomaniacs?\n\nThey always take things literally.',
        'How do you keep a bagel from getting away?\n\nPut lox on it.',
        'A man tells his doctor, “Doc, help me. I’m addicted to Twitter!”\n\nThe doctor replies, “Sorry, I don’t follow you…”',
        'What kind of exercise do lazy people do?\n\nDiddly-squats.',
        'Why don’t Calculus majors throw house parties?\n\nBecause you should never drink and derive.',
        'What do you call a parade of rabbits hopping backwards?\n\nA receding hare-line.',
        'What does Charles Dickens keep in his spice rack?\n\nThe best of thymes, the worst of thymes.',
        'What’s the different between a cat and a comma?\n\nA cat has claws at the end of paws; A comma is a pause at the end of a clause.',
        'Why should the number 288 never be mentioned?\n\nIt’s two gross.',
        'What did the Tin Man say when he got run over by a steamroller?\n\n“Curses! Foil again!”',
        'What did the bald man exclaim when he received a comb for a present?\n\nThanks— I’ll never part with it!',
        'What rhymes with orange\n\nNo it doesn’t.',
        'What did the left eye say to the right eye?\n\nBetween you and me, something smells.',
        'What do you call a fake noodle?\n\nAn impasta.',
        'How do you make a tissue dance?\n\nPut a little boogie in it.',
        'What did the 0 say to the 8?\n\nNice belt!',
        'What do you call a pony with a cough?\n\nA little horse.',
        'What did one hat say to the other?\n\nYou wait here. I’ll go on a head.',
        'What do you call a magic dog?\n\nA labracadabrador.',
        'What did the shark say when he ate the clownfish?\n\nThis tastes a little funny.',
        'What’s orange and sounds like a carrot?\n\nA parrot.',
        'Why can’t you hear a pterodactyl go to the bathroom?\n\nBecause the “P” is silent.',
        'I waited all night to see where the sun would rise…\n\n…And then it dawned on me.',
        'What did the pirate say when he turned 80?\n\nAye matey.',
        'Why did the frog take the bus to work today?\n\nHis car got toad away.',
        'What did the buffalo say when his son left for college?\n\nBison.',
        'What is an astronaut’s favourite part on a computer?\n\nThe space bar.',
        'Why did the yogurt go to the art exhibition?\n\nBecause it was cultured.',
        'What do you call an apology written in dots and dashes?\n\nRe-Morse code.',
        'Why did the hipster burn his mouth?\n\nHe drank the coffee before it was cool.',
        'Once my dog ate all the Scrabble tiles.\n\nHe kept leaving little messages around the house.',
        'Did you hear about the two people who stole a calendar?\n\nThey each got six months.',
        'Time flies like an arrow…\n\nFruit flies like a banana.',
        'How do poets say hello?\n\nHey, haven’t we metaphor?',
        'Where does Batman go to the bathroom?\n\nThe batroom.',
        'Why did the Oreo go to the dentist?\n\nBecause he lost his filling.',
        'What do you get from a pampered cow?\n\nSpoiled milk.',
        'Why is it annoying to eat next to basketball players?\n\nThey dribble all the time.',
        'What breed of dog can jump higher than buildings?\n\nAny dog, because buildings can’t jump.',
        'Why did the M&M go to school?\n\nIt wanted to be a Smartie.',
        'Why do bees have sticky hair?\n\nBecause they use honeycombs.',
        'What did the cop say to his belly button?\n\nYou’re under a vest.',
        'I got my daughter a fridge for her birthday.\n\nI can’t wait to see her face light up when she opens it.',
        'I poured root beer in a square glass.\n\nNow I just have beer.',
        'Why aren’t koalas actual bears?\n\nThey don’t meet the koalafications.',
        'Rest in peace to boiling water.\n\nYou will be mist.',
        'What do you call a rooster staring at a pile of lettuce?\n\nA chicken sees a salad.',
        'Why did the nurse need a red pen at work?\n\nIn case she needed to draw blood.',
        'How do you throw a space party?\n\nYou planet.',
        'The numbers 19 and 20 got into a fight.\n\n21.',
        'Why did it get so hot in the baseball stadium after the game?\n\nAll of the fans left.',
        'What do you call a train carrying bubblegum?\n\nA chew-chew train.',
        'Why did the math textbook visit the guidance counsellor?\n\nIt needed help figuring out its problems.',
        ]
