Ins = ['“All our dreams can come true, if we have the courage to pursue them.” – Walt Disney',
       '“The secret of getting ahead is getting started.” – Mark Twain',
       '“I’ve missed more than 9,000 shots in my career. I’ve lost almost 300 games. 26 times I’ve been trusted to take the game winning shot and missed. I’ve failed over and over and over again in my life and that is why I succeed.” – Michael Jordan',
       '“Don’t limit yourself. Many people limit themselves to what they think they can do. You can go as far as your mind lets you. What you believe, remember, you can achieve.” – Mary Kay Ash',
       '“The best time to plant a tree was 20 years ago. The second best time is now.” – Chinese Proverb',
       '“Only the paranoid survive.” – Andy Grove',
       '“It’s hard to beat a person who never gives up.” – Babe Ruth',
       '“I wake up every morning and think to myself, ‘how far can I push this company in the next 24 hours.’” – Leah Busque',
       '“If people are doubting how far you can go, go so far that you can’t hear them anymore.” – Michele Ruiz',
       '“We need to accept that we won’t always make the right decisions, that we’ll screw up royally sometimes – understanding that failure is not the opposite of success, it’s part of success.” – Arianna Huffington',
       '“Write it. Shoot it. Publish it. Crochet it, sauté it, whatever. MAKE.” – Joss Whedon',
       '“You’ve gotta dance like there’s nobody watching, love like you’ll never be hurt, sing like there’s nobody listening, and live like it’s heaven on earth.” ― William W. Purkey',
       '“Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten.”― Neil Gaiman',
       '“Everything you can imagine is real.”― Pablo Picasso',
       '“When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.” ― Helen Keller',
       '“Do one thing every day that scares you.”― Eleanor Roosevelt',
       '“It’s no use going back to yesterday, because I was a different person then.”― Lewis Carroll',
       '“Smart people learn from everything and everyone, average people from their experiences, stupid people already have all the answers.” – Socrates',
       '“Do what you feel in your heart to be right – for you’ll be criticized anyway.”― Eleanor Roosevelt',
       '“Happiness is not something ready made. It comes from your own actions.” ― Dalai Lama XIV',
       '“Whatever you are, be a good one.” ― Abraham Lincoln',
       '“The same boiling water that softens the potato hardens the egg. It’s what you’re made of. Not the circumstances.” – _-*™#7139',
       '“If we have the attitude that it’s going to be a great day it usually is.” – Catherine Pulsifier',
       '“You can either experience the pain of discipline or the pain of regret. The choice is yours.”  – _-*™#7139',
       '“Impossible is just an opinion.” – Paulo Coelho',
       '“Your passion is waiting for your courage to catch up.” – Isabelle Lafleche',
       '“Magic is believing in yourself. If you can make that happen, you can make anything happen.” – Johann Wolfgang Von Goethe',
       '“If something is important enough, even if the odds are stacked against you, you should still do it.” – Elon Musk',
       '“Hold the vision, trust the process.” – _-*™#7139',
       '“Don’t be afraid to give up the good to go for the great.” – John D. Rockefeller',
       '“People who wonder if the glass is half empty or full miss the point. The glass is refillable.” – _-*™#7139',
       '“Just another Magic Monday” – _-*™#7139',
       '“One day or day one. You decide.” – _-*™#7139',
       '“It’s Monday… time to motivate and make dreams and goals happen. Let’s go!” – Heather Stillufsen',
       '“It was a Monday and they walked on a tightrope to the sun.”― Marcus Zusak',
       '“Goodbye blue Monday.” ― Kurt Vonnegut',
       '“So. Monday. We meet again. We will never be friends—but maybe we can move past our mutual enmity toward a more-positive partnership.” ― Julio-Alexi Genao',
       '“When life gives you Monday, dip it in glitter and sparkle all day.” – Ella Woodword',
       'Monday c’est Mon Day - A rare quote.',
       'All Motivation Mondays need are a little more coffee and a lot more mascara - rare quote.',
       'I’m alive, motivated and ready to slay the day #MONSLAY - YOU',
       '“No one is to blame for your future situation but yourself. If you want to be successful, then become “Successful.”― Jaymin Shah',
       '“Things may come to those who wait, but only the things left by those who hustle.”― Abraham Lincoln',
       '“Everything comes to him who hustles while he waits.”― Thomas Edison',
       '“Every sucessful person in the world is a hustler one way or another. We all hustle to get where we need to be. Only a fool would sit around and wait on another man to feed him.” ― K’wan',
       '“Invest in your dreams. Grind now. Shine later.” – _-*™#7139',
       '“Hustlers don’t sleep, they nap.” – _-*™#7139',
       '“Greatness only comes before hustle in the dictionary.” – Ross Simmonds',
       '“Without hustle, talent will only carry you so far.” – Gary Vaynerchuk',
       '“Work like there is someone working twenty four hours a day to take it away from you.” – Mark Cuban',
       '“Hustle in silence and let your success make the noise.” – Unknown',
       '“We are what we repeatedly do. Excellence, then, is not an act, but a habit.” – Aristotle',
       '“If you’re offered a seat on a rocket ship, don’t ask what seat! Just get on.” – Sheryl Sandberg',
       '“I always did something I was a little not ready to do. I think that’s how you grow. When there’s that moment of ‘Wow, I’m not really sure I can do this,’ and you push through those moments, that’s when you have a breakthrough.” – Marissa Mayer',
       '“If you hear a voice within you say ‘you cannot paint,’ then by all means paint and that voice will be silenced.” – Vincent Van Gogh',
       '“How wonderful it is that nobody need wait a single moment before starting to improve the world.” – Anne Frank',
       '“Some people want it to happen, some wish it would happen, others make it happen.” – Michael Jordan',
       '“Great things are done by a series of small things brought together” – Vincent Van Gogh',
       '“If you hire people just because they can do a job, they’ll work for your money. But if you hire people who believe what you believe, they’ll work for you with blood and sweat and tears.” – Simon Sinek',
       '“Very often, a change of self is needed more than a change of scene.’ – A.C. Benson',
       '“Leaders can let you fail and yet not let you be a failure.” – Stanley McChrystal',
       '“It’s not the load that breaks you down, it’s the way you carry it.” – Lou Holtz',
       '“The hard days are what make you stronger.” – Aly Raisman',
       '“If you believe it’ll work out, you’ll see opportunities. If you don’t believe it’ll work out, you’ll see obstacles.” – Wayne Dyer',
       '“Keep your eyes on the stars, and your feet on the ground.” – Theodore Roosevelt',
       '“You can waste your lives drawing lines. Or you can live your life crossing them.” – Shonda Rhimes',
       '“You’ve got to get up every morning with determination if you’re going to go to bed with satisfaction.” – George Lorimer',
       '“I now tried a new hypothesis: It was possible that I was more in charge of my happiness than I was allowing myself to be.” – Michelle Obama',
       '“In a gentle way, you can shake the world.” – Mahatma Gandhi',
       '“If opportunity doesn’t knock, build a door.” – Kurt Cobain',
       '“Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.” – Roy T. Bennett',
       '“Work hard in silence, let your success be the noise.” – Frank Ocean',
       '“Don’t say you don’t have enough time. You have exactly the same number of hours per day that were given to Helen Keller, Pasteur, Michelangelo, Mother Teresa,',
       'Leonardo Da Vinci, Thomas Jefferson, and Albert Einstein.” – H. Jackson Brown Jr.',
       '“Hard work beats talent when talent doesn’t work hard.” – Tim Notke',
       '“If everything seems to be under control, you’re not going fast enough.” – Mario Andretti',
       '“Opportunity is missed by most people because it is dressed in overalls and looks like work.” – Thomas Edison',
       '“The only difference between ordinary and extraordinary is that little extra.” – Jimmy Johnson',
       '“The best way to appreciate your job is to imagine yourself without one.” – Oscar Wilde',
       '“Unsuccessful people make their decisions based on their current situations. Successful people make their decisions based on where they want to be.” – Benjamin Hardy',
       '“Never stop doing your best just because someone doesn’t give you credit.” – Kamari aka Lyrikal',
       '“Work hard for what you want because it won’t come to you without a fight. You have to be strong and courageous and know that you can do anything you put your mind to. If somebody puts you down or criticizes you, just keep on believing in yourself and turn it into something positive.” – Leah LaBelle',
       '“Work hard, be kind, and amazing things will happen.” – Conan O’Brien',
       '“The miracle is not that we do this work, but that we are happy to do it.” – Mother Teresa',
       '“Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway.” – Earl Nightingale',
       '“If you work on something a little bit every day, you end up with something that is massive.” – Kenneth Goldsmith',
       '“The big secret in life is that there is no secret. Whatever your goal, you can get there if you’re willing to work.” – Oprah Winfrey',
       '“If you cannot do great things, do small things in a great way.” – Napoleon Hill',
       '“Never allow a person to tell you no who doesn’t have the power to say yes.” – Eleanor Roosevelt',
       '“At any given moment you have the power to say: this is not how the story is going to end.” – Unknown',
       '“Amateus sit around and wait for inspiration. The rest of us just get up and go to work.” – Stephen King',
       '“Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do. If you haven’t found it yet, keep looking. Don’t settle. As with all matters of the heart, you’ll know when you find it.” – Steve Jobs',
       '“Nothing will work unless you do.” – Maya Angelou',
       '“Sometimes when you’re in a dark place you think you’ve been buried but you’ve actually been planted.” – Christine Caine',
       '“Don’t limit your challenges. Challenge your limits.” – Unknown',
       '“Whenever you find yourself doubting how far you can go, just remember how far you have come.” – Unknown',
       '“Everyone has inside them a piece of good news. The good news is you don’t know how great you can be! How much you can love! What you can accomplish! And what your potential is.” – Anne Frank',
       '“Some luck lies in not getting what you thought you wanted but getting what you have, which once you have got it you may be smart enough to see is what you would have wanted had you known.” – Garrison Keillor',
       '“Don’t quit yet, the worst moments are usually followed by the most beautiful silver linings. You have to stay strong, remember to keep your head up and remain hopeful.” – Unknown',
       '“When written in Chinese the word “crisis” is composed of two characters – one represents danger and the other represents opportunity.” – John F Kennedy',
       '“Good. Better. Best. Never let it rest. ‘Til your good is better and your better is best.” – St. Jerome.',
       '“In the middle of every difficulty lies opportunity.” – Albert Einstein',
       '“Start where you are. Use what you have. Do what you can.” – Arthur Ashe',
       '“Dreams don’t work unless you do.” – John C. Maxwell',
       '“Go the extra mile. It’s never crowded there.” – Dr. Wayne D. Dyer',
       '“Keep your face always toward the sunshine – and shadows will fall behind you.” – Walt Whitman',
       '“What defines us is how well we rise after falling.” – Lionel from Maid in Manhattan Movie',
       'H.O.P.E. = Hold On. Pain Ends.',
       'Make each day your masterpiece. – John Wooden',
       '“Wherever you go, go with all your heart” – Confucius',
       '“Turn your wounds into wisdom” – Oprah',
       '“We can do anything we want to if we stick to it long enough.” – Helen Keller',
       '“Begin anywhere.” – John Cage',
       '“Success is no accident. It is hard work, perseverance, learning, studying, sacrifice and most of all, love of what you are doing or learning to do.” – Pele',
       '“Would you like me to give you a formula for success? It’s quite simple, really: Double your rate of failure. You are thinking of failure as the enemy of success. But it isn’t at all. You can be discouraged by failure or you can learn from it, so go ahead and make mistakes. Make all you can. Because remember that’s where you will find success.” – Thomas J. Watson',
       '“Every champion was once a contender that didn’t give up.” – Gabby Douglas',
       '“To be a champion, I think you have to see the big picture. It’s not about winning and losing; it’s about every day hard work and about thriving on a challenge. It’s about embracing the pain that you’ll experience at the end of a race and not being afraid. I think people think too hard and get afraid of a certain challenge.” – Summer Sanders',
       'Don’t dream about success. Get out there and work for it.',
       '“The difference between successful people and very successful people is that very successful people say ‘no’ to almost everything.” – Warren Buffett',
       'You can cry, scream, and bang your head in frustration but keep pushing forward. It’s worth it.',
       '“I hated every minute of training, but I said, ‘Don’t quit. Suffer now and live the rest of your life as a champion.” – Muhammad Ali',
       '“Opportunities don’t happen. You create them.” – Chris Grosser',
       '“Success is liking yourself, liking what you do, and liking how you do it.” – Maya Angelou',
       '“If you obey all the rules, you miss all the fun.” – Katharine Hepburn',
       '“You were born to be a player. You were meant to be here. This moment is yours.” – Herb Brooks',
       '“Life is not what you alone make it. Life is the input of everyone who touched your life and every experience that entered it. We are all part of one another.” – Yuri Kochiyama',
       '“When you reach the end of your rope, tie a knot and hang out.” – Abraham Linco',
       '“Never regret anything that made you smile.” – Mark Twain',
       '“You must do the thing you think you cannot do.” – Eleanor Roosevelt',
       '“If you want to fly give up everything that weighs you down.” – Buddha',
       '“Doubt kills more dreams than failure ever will.” – Suzy Kassem',
       '“I never lose. Either I win or learn.” – Nelson Mandela',
       '“Today is your opportunity to build the tomorrow you want.” – Ken Poirot',
       '“Getting over a painful experience is much like crossing the monkey bars. You have to let go at some point in order to move forward.” – C.S. Lewis',
       '“Focus on being productive instead of busy.” – Tim Ferriss',
       '“You don’t need to see the whole staircase, just take the first step.” – Martin Luther King Jr.',
       '“It’s not all sunshine and rainbows, but a good amount of it actually is.” – Unknown',
       'When someone says you can’t do it, do it twice and take pictures.',
       '“I didn’t get there by wishing for it, but by working for it.” – Estee Lauder',
       '“She remembered who she was and the game changed.” – Lalah Deliah',
       '“If you’re too comfortable, it’s time to move on. Terrified of what’s next? You’re on the right track.” – Susan Fales-Hill',
       '“Be happy with what you have while working for what you want.” – Helen Keller',
       '“Sunshine all the time makes a desert.” – Arabic Proverb',
       '“The big lesson in life is never be scared of anyone or anything.” – Frank Sinatra',
       'You’re so much stronger than your excuses',
       'Don’t compare yourself to others. Be like the sun and the moon and shine when it’s your time.',
       'Don’t Quit',
       'Don’t tell everyone your plans, instead show them your results.',
       '“I choose to make the rest of my life, the best of my life.” – Louise Hay',
       '“Nothing can dim the light that shines from within.” – Maya Angelou',
       '“Be so good they can’t ignore you.” – Steve Martin',
       '“Take criticism seriously, but not personally. If there is truth or merit in the criticism, try to learn from it. Otherwise, let it roll right off you.” – Hillary Clinton',
       '“This is a reminder to you to create your own rule book, and live your life the way you want it.” – Reese Evans',
       '“If you don’t get out of the box you’ve been raised in, you won’t understand how much bigger the world is.” – Angelina Jolie',
       '“Do the best you can. No one can do more than that.” – John Wooden',
       '“Do what you can, with what you have, where you are.” – Theodore Roosevelt',
       '‘It’s never too late to be what you might’ve been.” – George Eliot',
       '“If you can dream it, you can do it.” – Walt Disney',
       '“Trust yourself that you can do it and get it.” – Baz Luhrmann',
       '“Don’t let what you can’t do interfere with what you can do.” – Unknown',
       '“You can do anything you set your mind to.” – Benjamin Franklin',
       '“All we can do is the best we can do.” – David Axelrod',
       '“You never know what you can do until you try.” – William Cobbett',
       '“Twenty years from now you’ll be more disappointed by the things you did not do than the ones you did.” – Mark Twain',
       '“I am thankful for all of those who said NO to me. It’s because of them I’m doing it myself.” – Wayne W. Dyer',
       'It’s okay to outgrow people who don’t grow. Grow tall anyways.',
       'When you feel like giving up just remember that there are a lot of people you still have to prove wrong.',
       '“The world is full of nice people. If you can’t find one, be one.” – Nishan Panwar',
       '“Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. Never let anyone bring you down. You got to keep going.” – Chantal Sutherland',
       '“A walk to a nearby park may give you more energy and inspiration in life than spending two hours in front of a screen.” – Tsang Lindsay',
       '“If you can’t do anything about it then let it go. Don’t be a prisoner to things you can’t change.” – Tony Gaskins',
       '“You can’t go back and change the beginning, but you can start where you are and change the ending.” – C.S. Lewis',
       '“Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.” – Rumi',
       '“I can and I will. Watch me.” – Carrie Green',
       '“Try not to become a man of success, but rather become a man of value.” – Albert Einstein',
       '“A winner is a dreamer who never gives up.” – Nelson Mandela',
       '“If you don’t have a competitive advantage, don’t compete.” – Jack Welch',
       '“The only thing standing in the way between you and your goal is the BS story you keep telling yourself as to why you can’t achieve it.” – Jordan Belfort',
       '“What is life without a little risk?” – J.K. Rowling',
       '“Only do what your heart tells you.” – Princess Diana',
       '“If it’s a good idea, go ahead and do it. It’s much easier to apologize than it is to get permission.” – Grace Hopper',
       '“I attribute my success to this: I never gave or took an excuse.” – Florence Nightingale',
       '“The question isn’t who is going to let me; it’s who is going to stop me.” – Ayn Rand',
       '“A surplus of effort could overcome a deficit of confidence.” – Sonia Sotomayer',
       '“And, when you want something, all the universe conspires in helping you to achieve it.” ― Paulo Coelho, The Alchemist',
       '“Your playing small does not serve the world. There is nothing enlightened about shrinking so that other people won’t feel insecure around you. We are all meant to shine, as children do.” – Marianne Williamson, A Return to Love: Reflections on the Principles of “A Course in Miracles”',
       '“Don’t think or judge, just listen.”― Sarah Dessen,',
       '“I can be changed by what happens to me. But I refuse to be reduced by it.” – Maya Angelou, Letter to My Daughter',
       '“Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.” ― Martin Luther King Jr., A Testament of Hope: The Essential Writings and Speeches',
       '“You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose. You’re on your own. And you know what you know. And YOU are the one who’ll decide where to go…” ― Dr. Seuss, Oh, the Places You’ll Go!',
       '“It’s the possibility of having a dream come true that makes life interesting.” ― Paulo Coelho, The Alchemist',
       '“There is some good in this world, and it’s worth fighting for.” – J.R.R. Tolkien, The Two Towers',
       '“Learn to light a candle in the darkest moments of someone’s life. Be the light that helps others see; it is what gives life its deepest significance.”― Roy T. Bennett, The Light in the Heart',
       '“Atticus, he was real nice.” “Most people are, Scout, when you finally see them.” ― Harper Lee, To Kill a Mockingbird',
       '“Oh yes, the past can hurt. But the way I see it, you can either run from it or learn from it.” – The Lion King',
       '“We’re on the brink of adventure, children. Don’t spoil it with questions.” – Mary Poppins',
       '“Life moves pretty fast. If you don’t stop and look around once in a while, you could miss it.”– Ferris Bueller',
       '“I just wanna let them know that they didn’t break me.” – Pretty in Pink',
       '“I’m going to make him an offer he can’t refuse.” – The Godfather',
       '“No one has ever made a difference by being like everyone else.” – The Greatest Showman',
       '“Spend a little more time trying to make something of yourself and a little less time trying to impress people.” – The Breakfast Club',
       '“The problem is not the problem. The problem is your attitude about the problem.” – Pirates of the Caribbean',
       '“Remember you’re the one who can fill the world with sunshine.” – Snow White',
       '“You’ll have bad times, but it’ll always wake you up to the good stuff you weren’t paying attention to.” – Good Will Hunting',
       '“And when you get the choice to sit it out or dance… I hope you dance.” – I Hope You Dance, Lee Ann Womack',
       '“Just because it burns doesn’t mean you’re gonna die you’ve gotta get up and try.” – Try, P!nk',
       '“Life’s a game made for everyone and love is the prize” – Wake Me Up, Avicii',
       '“It’s a new dawn, it’s a new day, it’s a life for me and I’m feeling good.” – Feeling Good, Michael Buble',
       '“Today is where your book begins, the rest is still unwritten.” – Unwritten, Natasha Bedingfield',
       '“A million dreams for the world we’re gonna make’ – The Greatest Showman',
       '“It’s my life It’s now or never I ain’t gonna live forever I just want to live while I’m alive” – It’s My Life, Bon Jovi',
       '“I could build a castle out of all the bricks they threw at me” – New Romantics, Taylor Swift',
       '“Cause the grass is greener under me bright as technicolor, I can tell that you can see” – Sorry Not Sorry, Demi Lovato',
       '“Every day women and men become legends” – Glory, John Legend and Common',
       '“On my own I will just create and if it works, it works. And if it doesn’t, I’ll just create something else. I don’t have any limitations on what I think I could do or be.” – Oprah Winfrey',
       '“We realize the importance of our voices only when we are silenced.” – Malala Yousafzai',
       '“We need to accept that we won’t always make the right decisions, that we’ll screw up royally sometimes – understanding that failure is not the opposite of success, it’s part of success.” – Arianna Huffington',
       '“Don’t compromise yourself. You’re all you’ve got.” – Janis Joplin',
       '“When something I can’t control happens, I ask myself: Where is the hidden gift? Where is the positive in this?” – Sara Blakely',
       '“Doubt is a killer. You just have to know who you are and what you stand for. “ – Jennifer Lopez',
       '“Be a first rate version of yourself, not a second rate version of someone else.” – Judy Garland',
       '“Learn from the mistakes of others. You can’t live long enough to make them all yourself.” – Eleanor Roosevelt',
       '“I was smart enough to go through any door that opened.” – Joan Rivers',
       '“Done is better than perfect.” – Sheryl Sandberg',
       '“If your dreams don’t scare you, they are too small.” – Richard Branson',
       '“Today is your opportunity to build the tomorrow you want.” – Ken Poirot',
       '“What hurts you blesses you.” – Rumi',
       '‘Nothing is stronger than a broken man rebuilding himself.” – Unknown',
       '“I always thought it was me against the world and then one day I realized it’s just me against me.” – Kendrick Lamar',
       '“A man is not finished when he is defeated. He is finished when he quits.” – Richard Nixon',
       '“The world is changed by your example, not by your opinion.” – Paulo Coelho',
       '“If you don’t build your dream, someone else will hire you to help them build theirs.” – Dhirubhai Ambani',
       '“I’m not in this world to live up to your expectations and you’re not in this world to live up to mine.” – Bruce Lee',
       '“What’s right is what’s left if you do everything else wrong.” – Robin Williams',
       '“Be a fruitloop in a world of Cheerios.” – Unknown',
       '“Dream beautiful dreams, and then work to make those dreams come true.” – Spencer W. Kimball',
       '“Be the change you want to see in the world.” – Mahatma Gandhi',
       '“Believe you can and you will.” – Unknown',
       '“Do the right thing even when no one is looking.” – Unknown',
       '“Make today the day you learn something new.” –Unknown',
       '“Be silly, be honest, be kind.’ – Ralph Waldo Emerson',
       '“If you think someone could use a friend. Be one.” – Unknown',
       '“It’s not what happens to you but how you react to it that matters.” – Epictetus',
       '“You don’t have to be perfect to be amazing.” – Unknown',
       '“The best way to predict your future is to create it.” – Abraham Lincoln',
       '“Successful people are not gifted; they just work hard, then succeed on purpose.” – G.K. Nielson',
       '“Don’t watch the clock; do what it does. Keep going.” – Sam Levenson',
       '“Work until your rivals become idols.” – Drake',
       '“You can’t have a million dollar dream on a minimum wage work ethic.” – Unknown',
       '“You must do the kind of things you think you cannot do.” – Eleanor Roosevelt',
       '“It’s not what you do once in a while it’s what you do day in and day out that makes the difference.” – Jenny Craig',
       'Falling down is how we grow. Staying down is how we die.” – Brian Vaszily',
       '“Wealth isn’t about having a lot of money it’s about having a lot of options.” – Chris Rock',
       '“There may be people that have more talent than you, but there’s no excuse for anyone to work harder than you.” – Derek Jeter',
       '“Always be careful when you follow the masses. Sometimes the m is silent.” – Unknown',
       'Never let anyone treat you like you’re regular glue. You’re glitter glue.',
       '“If you fall – I’ll be there.” – Floor',
       '“When Plan “A” doesn’t work, don’t worry, you still have 25 more letters to go through.” – Unknown',
       '“If you think you’re too small to make a difference, try sleeping with a mosquito.” – Dalai Lama',
       '“If at first you don’t succeed, then skydiving isn’t for you.” – Steven Wright',
       '“A diamond is merely a lump of coal that did well under pressure.” – Unknown',
       '“I find television very educational. Every time someone turns it on, I go in the other room and read a book.’ – Groucho Marx',
       '“Opportunity does not knock, it presents itself when you beat down the door.” – Kyle Chandler',
       '“I have not failed. I’ve just found 10,000 ways that won’t work.” – Thomas A. Edison',
       '“You could rattle the stars,” she whispered. “You could do anything, if only you dared. And deep down, you know it, too. That’s what scares you most.” ― Sarah J. Maas',
       '“It is only when we take chances, when our lives improve. The initial and the most difficult risk that we need to take is to become honest. – Walter Anderson',
       '“The adventure of life is to learn. The purpose of life is to grow. The nature of life is to change. The challenge of life is to overcome. The essence of life is to care. The opportunity of like is to serve. The secret of life is to dare. The spice of life is to befriend. The beauty of life is to give.” – William Arthur Ward',
       '“When you know your worth, no one can make you feel worthless.” – Unknown',
       '“If you’ve never eaten while crying you don’t know what life tastes like.” – Johann Wolfgang von Goethe',
       '“If you judge people, you have no time to love them.” – Mother Teresa',
       '“Once you do know what the question actually is, you’ll know what the answer means.”– Douglas Adams',
       '“The two most important days in your life are the day you’re born and the day you find out why.” – Mark Twain',
       '“Nothing ever goes away until it teaches us what we need to know.” – Pema Chodron',
       '‘We can see through others only when we can see through ourselves.” – Bruce Lee',
       '“You don’t get paid for the hour. You get paid for the value you bring to the hour.” – JIm Rohn',
       '“Be an Encourager: When you encourage others, you boost their self-esteem, enhance their self-confidence, make them work harder, lift their spirits and make them successful in their endeavors. Encouragement goes straight to the heart and is always available. Be an encourager. Always.” ― Roy T. Bennett',
       '“Remember, you have been criticizing yourself for years and it hasn’t worked. Try approving of yourself and see what happens.” –Louise L Hay',
       '“Work hard and don’t give up hope. Be open to criticism and keep learning. Surround yourself with happy, warm and genuine people.” – Tena Desae',
       '“Stay true to yourself, yet always be open to learn. Work hard, and never give up on your dreams, even when nobody else believes they can come true but you. These are not cliches but real tools you need no matter what you do in life to stay focused on your path.” – Phillip Sweet',
       '“You can control two things: your work ethic and your attitude about anything.” – Ali Krieger',
       '“Success isn’t always about greatness. It’s about consistency. Consistent hard work leads to success. Greatness will come.” – Dwayne Johnson',
       '“One, remember to look up at the stars and not down at your feet. Two, never give up work. Work gives you meaning and purpose and life is empty without it. Three, if you are lucky enough to find love, remember it is there and don’t throw it away.” ― Stephen Hawking',
       '“Some women choose to follow men, and some women choose to follow their dreams. If you’re wondering which way to go, remember that your career will never wake up and tell you that it doesn’t love you anymore.” ― Lady Gaga',
       '“Read, read, read. Read everything — trash, classics, good and bad, and see how they do it. Just like a carpenter who works as an apprentice and studies the master. Read! You’ll absorb it. Then write. If it’s good, you’ll find out. If it’s not, throw it out of the window.”― William Faulkner',
       '“I really appreciate people who correct me, because without them, I might have been repeating mistakes for a long time.” – Mufti Menk',
       '“Motivation comes from working on things we care about.” – Sheryl Sandberg',
       '“If today you are a little bit better than you were yesterday, then that’s enough.” – David A. Bednar',
       '“Education is the most powerful weapon which you can use to change the world.” – Nelson Mandela',
       '“If you can’t make a mistake you can’t make anything.” – Marva Collin',
       '“Practice makes progress not perfect.” – Unknown',
       '“You may be disappointed if you fail, but you’ll be doomed if you don’t try.” – Beverly Sills',
       '“Failure is the tuition you pay for success.” – Walter Brunell',
       '“If we wait until we’re ready, we’ll be waiting for the rest of our lives.” – Lemony Snicket',
       '“Study while others are sleeping; work while others are loafing; prepare while others are playing; and dream while others are wishing.” – William Arthur Ward',
       '"The best revenge is massive success.” – Frank Sinatra',
       '“What’s on the other side of fear? Nothing.” – Jamie Foxx',
       '“Quitters never win. Winners never quit!” Dr. Irene C. Kassorla',
       '“It’s not your salary that makes you rich, it’s your spending habits.” – Charles A. Jaffe',
       '“If there is no wind, row.” – Latin Proverb',
       '“It’s never too late for a new beginning in your life.” – Joyce Meyers',
       ]

img = ['https://i.imgur.com/YctOUSU.jpeg',
       'https://i.imgur.com/auORyKI.jpeg',
       'https://i.imgur.com/lsVZyTU.jpeg',
       'https://i.imgur.com/tfg5hy4.jpeg',
       'https://i.imgur.com/gn9uhCt.jpeg',
       'https://i.imgur.com/GTHOtNN.jpeg',
       'https://i.imgur.com/7bVuQjg.png',
       'https://i.imgur.com/GtdJhZG.jpg',
       'https://i.imgur.com/1TnD4KV.jpeg',
       'https://i.imgur.com/VBjkct8.jpeg',
       'https://i.imgur.com/F6aaSK1.jpeg',
       'https://i.imgur.com/ZVNgLLj.jpeg',
       'https://i.imgur.com/gSfNFL2.jpeg',
       'https://i.imgur.com/7MTLbf9.jpeg',
       'https://i.imgur.com/CPy4NXz.jpeg',
       'https://discordapp.com/channels/740523643980873789/741292472784912426/741664224467615795',
       'https://i.imgur.com/hf12ZDG.png',
       'https://i.imgur.com/EFiaAf0.jpg',
       'https://i.imgur.com/hHwn1E9.jpg',
       'https://i.imgur.com/wQvXaDL.jpg',
       'https://i.imgur.com/YTzuvs5.jpg',
       'https://i.imgur.com/T8CW6G6.jpg',
       'https://i.imgur.com/MaizI8H.jpg',
       'https://i.imgur.com/abjxsg0.jpg',
       'https://i.imgur.com/RfHGYrx.jpg',
       'https://i.imgur.com/HpetrQ1.jpeg',
       'https://i.imgur.com/I5688qU.jpeg',
       'https://i.imgur.com/558vjYa.jpeg',
       'https://i.imgur.com/pBSzqtr.jpeg',
       'https://i.imgur.com/Dz08kBq.jpeg',
       'https://i.imgur.com/vGkEbI6.jpeg',
       'https://i.imgur.com/nHagKVW.jpeg',
       'https://i.imgur.com/A8alBT0.jpeg',
       'https://i.imgur.com/i5QtUIv.jpeg',
       'https://i.imgur.com/ouxWA1T.jpeg',
       'https://i.imgur.com/5ZcEpZL.jpeg',
       'https://i.imgur.com/6PrnjvD.jpeg',
       'https://i.imgur.com/dFTNDIJ.jpeg',
       'https://i.imgur.com/bR8iaTj.jpeg',
       'https://i.imgur.com/9ywbPNw.jpeg',
       'https://i.imgur.com/PkFrYtZ.jpeg',
       'https://i.imgur.com/2QQra5Q.jpeg',
       'https://i.imgur.com/W2B4Lwv.jpeg',
       'https://i.imgur.com/Id1GJcz.jpeg',
       'https://i.imgur.com/cHSBxRH.jpeg',
       'https://i.imgur.com/eoFEtTi.jpeg',
       'https://i.imgur.com/czdQ8Wb.jpeg',
       'https://i.imgur.com/lEWb0S1.jpeg',
       'https://i.imgur.com/cKjsc4k.jpeg',
       'https://i.imgur.com/fDese3y.jpeg',
       'https://i.imgur.com/MijlG7j.jpeg',
       'https://i.imgur.com/zUNb0cT.jpeg',
       'https://i.imgur.com/6oTVxmA.jpeg',
       'https://i.imgur.com/SxGPH0D.jpeg',
       'https://i.imgur.com/mAfAx1K.jpeg',
       'https://i.imgur.com/XHTSXsl.jpeg',
       'https://i.imgur.com/E0cm8gI.jpeg',
       'https://i.imgur.com/uUbpVNZ.jpeg',
       'https://i.imgur.com/HHr2IPT.jpeg',
       'https://i.imgur.com/KD5bVTz.jpeg',
       'https://i.imgur.com/vZAsAdL.jpg',
       'https://i.imgur.com/DovyBav.jpg',
       'https://i.imgur.com/IFBnJMi.jpg',
       ]
